 NUMPY is a fundamental library for scientific computing in python,it provides support for arrays and matrices to operate data structure.

In [3]:
!pip install numpy

In [ ]:
import numpy as np
### create arrays using numpy
## create a id array
arr1 =np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)  ### 1 dimension array

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
### two dimension array
arr2=np.array([3,6,5,9,2]) 
arr2.reshape(1,5) ## 1 row and 5 colums

array([[3, 6, 5, 9, 2]])

In [12]:
arr2=np.array([[3,6,5,9,2]]) 
arr2.shape

(1, 5)

In [ ]:
## 2d array
arr2=np.array([[3,6,5,9,2],[1,2,3,4,5]])
print(arr2)
print(arr2.shape)

[[3 6 5 9 2]
 [1 2 3 4 5]]
(2, 5)


In [22]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [29]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [32]:
### create identity metrics 
np.eye(4)


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
### numpy vectorized operation
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([12,23,11,14,15])

### ELEMENTS WISE ADDITION,substraction and multiplication
print("addition:",arr1 + arr2)
print("subtraction:",arr1 - arr2)
print("multiplicction:",arr1 * arr2)

addition: [13 25 14 18 20]
subtraction: [-11 -21  -8 -10 -10]
multiplicction: [12 46 33 56 75]


In [ ]:
###  universal function (ufuncs)
arr=np.array([3,2,6,5,2])
## square root
print(np.sqrt(arr))

### exponential
print(np.exp(arr))
## sine
print(np.sin(arr))

### natural log

print(np.log(arr))

[1.73205081 1.41421356 2.44948974 2.23606798 1.41421356]
[ 20.08553692   7.3890561  403.42879349 148.4131591    7.3890561 ]
[ 0.14112001  0.90929743 -0.2794155  -0.95892427  0.90929743]
[1.09861229 0.69314718 1.79175947 1.60943791 0.69314718]


In [47]:
### array slicing and indexing
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("array:\n",arr)




array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [53]:
arr[0]

array([1, 2, 3, 4])

In [51]:
arr[0][0]

np.int64(1)

In [54]:
arr[1]

array([5, 6, 7, 8])

In [ ]:
arr[1:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [57]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [59]:
print(arr[0:2,2:])

[[3 4]
 [7 8]]


In [60]:
### modify array elements
arr [0,0] = 80
print(arr)

[[80  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [62]:
arr[1:]=70
print(arr)

[[80  2  3  4]
 [70 70 70 70]
 [70 70 70 70]]


In [66]:
### standard deviation
data = np.array([1,2,3,4,5,6,7,8,9,10])
mean = np.mean(data)
print("mean",mean)

median = np.median(data)
print("median",median)

std_dev = np.std(data)
print("standard deviation",std_dev)

variance = np.var(data)
print("variance",variance)

mean 5.5
median 5.5
standard deviation 2.8722813232690143
variance 8.25


In [72]:
### logical operation
data = np.array([1,2,3,4,5,6,7,8,9,10])
data> 5


array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [71]:
data [data>5]

array([ 6,  7,  8,  9, 10])

In [76]:
data [(data>=5) & (data<=8)]

array([5, 6, 7, 8])